// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8wEBPF_Y07YY6ikdXK6VT3XYRibvt9Y',
    appId: '1:766344524106:web:9862b8ab8bf58fd45991b3',
    messagingSenderId: '766344524106',
    projectId: 'time-keeper-535',
    authDomain: 'time-keeper-535.firebaseapp.com',
    storageBucket: 'time-keeper-535.appspot.com',
    measurementId: 'G-7KWB2MKM8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Jx3WGTW0DdaUWE3GBTwvDFsgVh6kpX4',
    appId: '1:766344524106:android:17386bde82abe0cd5991b3',
    messagingSenderId: '766344524106',
    projectId: 'time-keeper-535',
    storageBucket: 'time-keeper-535.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiXTFTh4penLPz6PMoO9pEcfTrla9gWJQ',
    appId: '1:766344524106:ios:363e057075d02d4c5991b3',
    messagingSenderId: '766344524106',
    projectId: 'time-keeper-535',
    storageBucket: 'time-keeper-535.appspot.com',
    iosClientId: '766344524106-i2ggr86ktn62cv991333lot09ouj73eh.apps.googleusercontent.com',
    iosBundleId: 'com.senyor.timeKeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiXTFTh4penLPz6PMoO9pEcfTrla9gWJQ',
    appId: '1:766344524106:ios:3d4295928b1256c75991b3',
    messagingSenderId: '766344524106',
    projectId: 'time-keeper-535',
    storageBucket: 'time-keeper-535.appspot.com',
    iosClientId: '766344524106-g8ha4prijos99bij2uf68ltdpr1sqfq5.apps.googleusercontent.com',
    iosBundleId: 'com.senyor.timeKeeper.RunnerTests',
  );
}
